### ISSUE TITLE
The REST client doesn't recognize IP addresses in subjectAltNames in the API server cert

### ISSUE THREAD

**Issue by guoshimin** [kubernetes-client/python-base#10]
On GKE, the master has a self-signed cert with its IP addresses in the subjectAltNames. The REST client seems to ignore those.
```
2017-06-08 21:57:56,534 ERROR Certificate did not match expected hostname: 146.xxx.yyy.144. Certificate: {'notAfter': 'May 24 23:19:20 2021 GMT', 'subjectAltName': (('DNS', 'kubernetes'), ('DNS', 'kubernetes.default'), ('DNS', 'kubernetes.default.svc'), ('DNS', 'kubernetes.default.svc.cluster.local'), ('IP Address', '146.xxx.yyy.144'), ('IP Address', '10.3.240.1')), 'subject': ((('commonName', u'146.xxx.yyy.144'),),)}
Traceback (most recent call last):
  File "build.py", line 45, in <module>
    resp = api_instance.list_namespaced_pod('jenkins')
  File "/home/shimin/env/local/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 12382, in list_namespaced_pod
    (data) = self.list_namespaced_pod_with_http_info(namespace, **kwargs)
  File "/home/shimin/env/local/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 12481, in list_namespaced_pod_with_http_info
    collection_formats=collection_formats)
  File "/home/shimin/env/local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 329, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/home/shimin/env/local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 153, in __call_api
    _request_timeout=_request_timeout)
  File "/home/shimin/env/local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 361, in request
    headers=headers)
  File "/home/shimin/env/local/lib/python2.7/site-packages/kubernetes/client/rest.py", line 240, in GET
    query_params=query_params)
  File "/home/shimin/env/local/lib/python2.7/site-packages/kubernetes/client/rest.py", line 217, in request
    raise ApiException(status=0, reason=msg)
kubernetes.client.rest.ApiException: (0)
Reason: SSLError
hostname '146.xxx.yyy.144' doesn't match either of 'kubernetes', 'kubernetes.default', 'kubernetes.default.svc', 'kubernetes.default.svc.cluster.local'
```

**Comment by guoshimin** [comment]
[sorry about the edits. Hit submit by accident.]

**Comment by guoshimin** [comment]
Oh duplicate of https://github.com/kubernetes-incubator/client-python/issues/165
