### ISSUE TITLE
AttributeError: 'ConfigNode' object has no attribute 'get'

### ISSUE THREAD

**Issue by markvr** [kubernetes-client/python-base#179]
Using latest pre-release version ` kubernetes-11.0.0b2` with `Python 3.6.5` on `Windows 10` against an Azuze Kubernetes Service cluster, configured using Azure AD for authentication:

I receive the error:

```
Traceback (most recent call last):
  File "check_neptune2.py", line 4, in <module>
    config.load_kube_config()
  File "C:\programs\Python36\lib\site-packages\kubernetes\config\kube_config.py", line 667, in load_kube_config
    loader.load_and_set(config)
  File "C:\programs\Python36\lib\site-packages\kubernetes\config\kube_config.py", line 474, in load_and_set
    self._load_authentication()
  File "C:\programs\Python36\lib\site-packages\kubernetes\config\kube_config.py", line 205, in _load_authentication
    if self._load_auth_provider_token():
  File "C:\programs\Python36\lib\site-packages\kubernetes\config\kube_config.py", line 222, in _load_auth_provider_token
    return self._load_azure_token(provider)
  File "C:\programs\Python36\lib\site-packages\kubernetes\config\kube_config.py", line 241, in _load_azure_token
    self._refresh_azure_token(provider['config'])
  File "C:\programs\Python36\lib\site-packages\kubernetes\config\kube_config.py", line 256, in _refresh_azure_token
    apiserver_id = config.get(
AttributeError: 'ConfigNode' object has no attribute 'get'
```

**Comment by roycaihw** [comment]
could you provide the kubeconfig file that you're using? 

cc @scottilee

**Comment by scottilee** [comment]
https://github.com/kubernetes-client/python-base/blob/master/config/kube_config.py#L221

**Comment by markvr** [comment]
Apologies for the delay, an example redacted file is:

```apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1C...LS0tLS0K
    server: https://neptune2-p-neptune2-preprod-64a49a-d05ea01a.hcp.westeurope.azmk8s.io:443
  name: neptune2-preprod
contexts:
- context:
    cluster: neptune2-preprod
    user: clusterUser_neptune2-preprod_neptune2-preprod
  name: neptune2-preprod
current-context: neptune2-preprod
kind: Config
preferences: {}
users:
- name: clusterUser_neptune2-preprod_neptune2-preprod
  user:
    auth-provider:
      config:
        access-token: eyJ...GA
        apiserver-id: d6af598f-8e23-4eb3-9424-302f29d0bec5
        client-id: c461b77b-c921-4412-aa47-dafcadb500ca
        environment: AzurePublicCloud
        expires-in: '3600'
        expires-on: '1575377675'
        refresh-token: AQA...IAA
        tenant-id: b2e47f30-cd7d-4a4e-a5da-b18cf1a4151b
      name: azure
- name: clusterAdmin_neptune2-dev_neptune2-dev
  user:
    client-certificate-data: LS0t...Cg==
    client-key-data: LS0...S0K
    token: SUi...f6O
```
