### ISSUE TITLE
Strange error when using this in high-load on PyPy

### ISSUE THREAD

**Issue by yuvipanda** [kubernetes-client/python-base#23]
Heya!

I've been load testing our JupyterHub kubespawner with high loads, and have recently been testing on PyPy.

I've discovered this error show up:

```
[E 2017-07-23 04:16:26.938 JupyterHub base:344] Failed to add user <User(benchmark-8-3-zrm9m38@10.244.4.119:8888)> to proxy!
    Traceback (most recent call last):
      File "/srv/venv/site-packages/jupyterhub/handlers/base.py", line 342, in finish_user_spawn
        yield self.proxy.add_user(user)
      File "/srv/venv/site-packages/jupyterhub/proxy.py", line 242, in add_user
        {'user': user.name}
      File "/srv/venv/site-packages/kubespawner/proxy.py", line 150, in add_route
        kind='endpoints'
      File "/srv/venv/site-packages/kubespawner/proxy.py", line 118, in create_if_required
        body=body
      File "/usr/local/pypy/lib-python/3/concurrent/futures/_base.py", line 398, in result
        return self.__get_result()
      File "/usr/local/pypy/lib-python/3/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/usr/local/pypy/lib-python/3/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/srv/venv/site-packages/kubespawner/proxy.py", line 96, in asynchronize
        return method(*args, **kwargs)
      File "/srv/venv/site-packages/kubernetes/client/apis/core_v1_api.py", line 5517, in create_namespaced_endpoints
        (data) = self.create_namespaced_endpoints_with_http_info(namespace, body, **kwargs)
      File "/srv/venv/site-packages/kubernetes/client/apis/core_v1_api.py", line 5607, in create_namespaced_endpoints_with_http_info
        collection_formats=collection_formats)
      File "/srv/venv/site-packages/kubernetes/client/api_client.py", line 329, in call_api
        _return_http_data_only, collection_formats, _preload_content, _request_timeout)
      File "/srv/venv/site-packages/kubernetes/client/api_client.py", line 153, in __call_api
        _request_timeout=_request_timeout)
      File "/srv/venv/site-packages/kubernetes/client/api_client.py", line 383, in request
        body=body)
      File "/srv/venv/site-packages/kubernetes/client/rest.py", line 275, in POST
        body=body)
      File "/srv/venv/site-packages/kubernetes/client/rest.py", line 175, in request
        headers=headers)
      File "/srv/venv/site-packages/urllib3/request.py", line 70, in request
        **urlopen_kw)
      File "/srv/venv/site-packages/urllib3/request.py", line 148, in request_encode_body
        return self.urlopen(method, url, **extra_kw)
      File "/srv/venv/site-packages/urllib3/poolmanager.py", line 321, in urlopen
        response = conn.urlopen(method, u.request_uri, **kw)
      File "/srv/venv/site-packages/urllib3/connectionpool.py", line 600, in urlopen
        chunked=chunked)
      File "/srv/venv/site-packages/urllib3/connectionpool.py", line 345, in _make_request
        self._validate_conn(conn)
      File "/srv/venv/site-packages/urllib3/connectionpool.py", line 844, in _validate_conn
        conn.connect()
      File "/srv/venv/site-packages/urllib3/connection.py", line 346, in connect
        _match_hostname(cert, self.assert_hostname or hostname)
      File "/srv/venv/site-packages/urllib3/connection.py", line 356, in _match_hostname
        match_hostname(cert, asserted_hostname)
      File "/usr/local/pypy/lib-python/3/ssl.py", line 288, in match_hostname
        if host_ip is not None and _ipaddress_match(value, host_ip):
      File "/usr/local/pypy/lib-python/3/ssl.py", line 259, in _ipaddress_match
        ip = ipaddress.ip_address(ipname.rstrip())
      File "/usr/local/pypy/lib-python/3/ipaddress.py", line 54, in ip_address
        address)
    ValueError: '10.0.0.1\x005.1' does not appear to be an IPv4 or IPv6 address
```

Not sure what that is and why it'd think the IP is that. I assume it's trying to talk to the kubernetes API, which is at 10.0.0.1 - not sure where the \x005.1 comes from.

This could be a bug in PyPy - unsure! I'll try to repro this in cpython.

**Comment by yuvipanda** [comment]
Closing, most likely a PyPy bug! Filed as https://bitbucket.org/pypy/pypy/issues/2615/this-looks-like-a-thread-safety-bug - sorry for the noise!
