### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2

### ISSUE THREAD

**Issue by tchelovilar** [kubernetes-client/python-base#245]
Hi, I got a decode error using the function w.stream to get the log stream:

https://github.com/kubernetes-client/python-base/blob/0d4f822f4f654361764a6f8dcf7ca9bf5bbce3f9/watch/watch.py#L58

Follow the traceback:
```
  0%|          | 0/200286 [00:00<?, ?it/s]Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.
Traceback (most recent call last):
  File "_model-train-and-release-cicd/auto-anubis/follow-job.py", line 135, in <module>
    main()
  File "_model-train-and-release-cicd/auto-anubis/follow-job.py", line 91, in main
    for line in w.stream(
  File "/usr/local/lib/python3.8/dist-packages/kubernetes/watch/watch.py", line 165, in stream
    for line in iter_resp_lines(resp):
  File "/usr/local/lib/python3.8/dist-packages/kubernetes/watch/watch.py", line 58, in iter_resp_lines
    seg = seg.decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 32767: unexpected end of data
```

Thank you in advance :)

**Comment by roycaihw** [comment]
Could you share more of your code and what log stream you were getting?

**Comment by tchelovilar** [comment]
Hi @roycaihw ,

Thank you for your time.

This is the snippet of the code that I use to follow the log:
```
        w = watch.Watch()
        start_time = time()

        try:
            for line in w.stream(
                func=k8s.read_namespaced_pod_log,
                name=POD_NAME,
                namespace=NAMESPACE,
                follow=True,
            ):
                print(line)
                if (time() - start_time) > int(FOLLOW_LOG_TIME):
                    w.stop()
        except UnicodeDecodeError as error:
            print(error)
```

Follow a copy of the log, the problem happens at line 17:
https://github.com/tchelovilar/test-actions/blob/master/log2#L17

And the last traceback:
```
   0%|          | 0/200286 [00:00<?, ?it/s]Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.

  0%|          | 0/200286 [00:00<?, ?it/s]Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.

  0%|          | 0/200286 [00:00<?, ?it/s]Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.
Traceback (most recent call last):
  File "_model-train-and-release-cicd/auto-anubis/follow-job.py", line 135, in <module>
    main()
  File "_model-train-and-release-cicd/auto-anubis/follow-job.py", line 91, in main
    for line in w.stream(
  File "/usr/local/lib/python3.8/dist-packages/kubernetes/watch/watch.py", line 165, in stream
    for line in iter_resp_lines(resp):
  File "/usr/local/lib/python3.8/dist-packages/kubernetes/watch/watch.py", line 58, in iter_resp_lines
    seg = seg.decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 32767: unexpected end of data
```
